[package]
name = "rqbnb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["secrets", "json"] }
regex = "1"
sqlite = "0.30.3"
chrono = "0.4.23"

