/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qbnb;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  public static final String TEST_PATH = "/db/test.json";

  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
